# Elastic Config Operator
# Ref: https://helm.sh/docs/topics/charts/#the-chartyaml-file
apiVersion: v2
name: elastic-config-operator
type: application
description: >-
  A Kubernetes operator to manage Elasticsearch and OpenSearch configuration 
  (ILM/ISM policies, Index Templates, Snapshot Lifecycle Policies, 
  Snapshot Repositories, and Cluster Settings) as Kubernetes Custom Resources.
version: 0.0.1 # chart version
appVersion: "0.0.1" # elastic-config-operator version
kubeVersion: ">=1.11.3-0" # kubernetes version
home: https://github.com/freepik-company/elastic-config-operator
sources:
  - https://github.com/freepik-company/elastic-config-operator
keywords:
  - freepik
  - elasticsearch
  - eck
  - elastic
  - ilm
  - slm
  - operator
  - gitops
maintainers:
  - name: Daniel Fradejas
    email: fradejasdaniel@gmail.com
