# ECK Config Operator
# Ref: https://helm.sh/docs/topics/charts/#the-chartyaml-file
apiVersion: v2
name: eck-config-operator
type: application
description: >-
  A Kubernetes operator to manage Elasticsearch configuration 
  (ILM policies, Index Templates, Snapshot Lifecycle Policies, 
  and Snapshot Repositories) as Kubernetes Custom Resources.
version: 1.0.0 # chart version
appVersion: "1.0.0" # eck-config-operator version
kubeVersion: ">=1.11.3-0" # kubernetes version
home: https://github.com/freepik-company/eck-config-operator
sources:
  - https://github.com/freepik-company/eck-config-operator
keywords:
  - freepik
  - elasticsearch
  - eck
  - elastic
  - ilm
  - slm
  - operator
  - gitops
maintainers:
  - name: Daniel Fradejas
    email: fradejasdaniel@gmail.com
