apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "eck-config-operator.fullname" . }}-manager
  labels:
    {{- include "eck-config-operator.labels" . | nindent 4 }}
rules:
{{- if .Values.controller.rbac.clusterWideSecrets }}
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
{{- end }}
- apiGroups:
  - elasticsearch.k8s.elastic.co
  resources:
  - elasticsearches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - eck-config-operator.freepik.com
  resources:
  - clustersettings
  - indexlifecyclepolicies
  - indexstatemanagements
  - indextemplates
  - snapshotlifecyclepolicies
  - snapshotrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eck-config-operator.freepik.com
  resources:
  - clustersettings/finalizers
  - indexlifecyclepolicies/finalizers
  - indexstatemanagements/finalizers
  - indextemplates/finalizers
  - snapshotlifecyclepolicies/finalizers
  - snapshotrepositories/finalizers
  verbs:
  - update
- apiGroups:
  - eck-config-operator.freepik.com
  resources:
  - clustersettings/status
  - indexlifecyclepolicies/status
  - indexstatemanagements/status
  - indextemplates/status
  - snapshotlifecyclepolicies/status
  - snapshotrepositories/status
  verbs:
  - get
  - patch
  - update
