{{- if and (not .Values.controller.rbac.clusterWideSecrets) .Values.controller.rbac.secretsNamespaces }}
{{- range .Values.controller.rbac.secretsNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "elastic-config-operator.fullname" $ }}-secrets-reader
  namespace: {{ . }}
  labels:
    {{- include "elastic-config-operator.labels" $ | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "elastic-config-operator.fullname" $ }}-secrets-reader
  namespace: {{ . }}
  labels:
    {{- include "elastic-config-operator.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "elastic-config-operator.fullname" $ }}-secrets-reader
subjects:
- kind: ServiceAccount
  name: {{ include "elastic-config-operator.serviceAccountName" $ }}
  namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}

